export const GAMEOPTIONS_RESET = 1;
export const GAMEOPTIONS_CHANGE_SELECTION = 4;
export const GAMEOPTIONS_MODIFY_MAX_WEIGHT = 7;
export const GAMEOPTIONS_UPDATE_MAX_WEIGHT = 10;
export const GAMEOPTIONS_ADD_QUESTION = 2;
export const GAMEOPTIONS_REMOVE_QUESTION = 3;
export const GAMEOPTIONS_MODIFY_QUESTION = 5;
export const GAMEOPTIONS_MODIFY_QUESTION_DATA = 6;

export const BACKEND_SETCONNECTION = "SC";
export const BACKEND_SETACCESSTOKEN = "AK";